version: "3.9"

networks:
  tripmate-network:
    driver: bridge

services:

  postgres-keycloak:
    image: postgres:16
    container_name: postgres-keycloak
    restart: always
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    volumes:
      - keycloak_db:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - tripmate-network

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.3
    container_name: keycloak
    command:
      - start-dev
      - --import-realm
    depends_on:
      - postgres-keycloak
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres-keycloak:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak

      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin

      KC_HTTP_PORT: 8080
    volumes:
      - ./keycloak:/opt/keycloak/data/import
    ports:
      - "8080:8080"
    networks:
      - tripmate-network

  postgres-app:
    image: postgres:16
    container_name: postgres-app
    restart: always
    environment:
      POSTGRES_DB: appdb
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
    volumes:
      - app_db:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    networks:
      - tripmate-network

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123

#  eureka-server:
#    build:
#      context: .
#      dockerfile: eureka-server/Dockerfile
#
#    container_name: eureka-server
#    ports:
#      - "8761:8761"
#    networks:
#      - tripmate-network
#
#  apigw:
#    build:
#      context: .
#      dockerfile: apigw/Dockerfile
#
#    container_name: apigw
#    environment:
#      SPRING_PROFILES_ACTIVE: docker
#      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: http://keycloak:8080/realms/tripmate
#      KEYCLOAK_CLIENT_SECRET: user-service-secret
#    ports:
#      - "8083:8083"
#    networks:
#      - tripmate-network
#    depends_on:
#      - keycloak
#      - eureka-server
#
#  user-service:
#    build:
#      context: .
#      dockerfile: user-service/Dockerfile
#
#    container_name: user-service
#    environment:
#      SPRING_PROFILES_ACTIVE: docker
#      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-app:5432/appdb
#      SPRING_DATASOURCE_USERNAME: app
#      SPRING_DATASOURCE_PASSWORD: app
#      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
#      KEYCLOAK_REALM: tripmate
#      KEYCLOAK_CLIENT_ID: user-service
#      KEYCLOAK_CLIENT_SECRET: user-service-secret
#      KEYCLOAK_URL: http://keycloak:8080
#    ports:
#      - "8082:8082"
#    networks:
#      - tripmate-network
#    depends_on:
#      - postgres-app
#      - keycloak
#      - eureka-server
#  notification:
#    build:
#      context: .
#      dockerfile: notification/Dockerfile
#
#    container_name: notification
#    environment:
#      SPRING_PROFILES_ACTIVE: docker
#      MAIL_USERNAME: ${MAIL_USERNAME}
#      MAIL_PASSWORD: ${MAIL_PASSWORD}
#    ports:
#      - "8081:8081"
#    networks:
#      - tripmate-network
#    depends_on:
#      - postgres-app
#      - keycloak
#      - eureka-server

volumes:
  keycloak_db:
  app_db:
