server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/appdb
    username: app
    password: app
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  jackson:
    serialization:
      write-dates-as-timestamps: false
  application:
    name: user-service

tripmate:
  keycloak:
    base-url: http://localhost:8080
    realm: tripmate
    client-id: tripmate-backend
    client-secret: ${KEYCLOAK_CLIENT_SECRET}
    admin-username: admin
    admin-password: admin

spring.security.oauth2.resourceserver.jwt:
  issuer-uri: ${tripmate.keycloak.base-url}/realms/${tripmate.keycloak.realm}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
