server:
  port: 8083


tripmate:
  keycloak:
    base-url: http://localhost:8080
    realm: tripmate
    client-id: tripmate-backend
    client-secret: ${KEYCLOAK_CLIENT_SECRET}
    admin-username: admin
    admin-password: admin

spring:
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: ${tripmate.keycloak.base-url}/realms/${tripmate.keycloak.realm}

  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: notification
              uri: lb://NOTIFICATION
              predicates:
                - Path=/api/notification/**
            - id: user-service
              uri: lb://USER-SERVICE
              predicates:
                - Path=/api/auth/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true